### ISSUE TITLE
test-only runs all tests in all projects if invoked directly from the command line

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#357]
If I run `sbt test-only *SingleTestSuite` from the command line with a multi module project, then sbt actually runs **all** the tests in **all** the projects.

Running `sbt` and then `test-only *SingleTestSuite` results in the expected behaviour, i.e. sbt searches all sub projects for tests that match the given pattern.

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#357](https://github.com/sbt/sbt/issues/357) for the full issue and to comment.

**Comment by morhook** [comment]
As @randomcoder said, you have to put quotes so that sbt can interpret just as one command:

```
sbt "test-only *SingleTestSuite"
```
