### ISSUE TITLE
Dependency Management in Scala: Now and Later

### ISSUE THREAD

**Issue by bblfish** [harrah/xsbt#634]
Hi, I saw your talk at NeScala. 
https://marakana.com/s/post/1418/dependency_management_in_scala_now_and_later_mark_harrah_video

I have had in the back of my mind for a while the possiblity of doing a build system using Linked Data. I wrote something up initially a while ago here:

  https://blogs.oracle.com/bblfish/entry/replacing_ant_with_rdf

In the mean time a lot has improved in RDF. [Turtle](http://www.w3.org/TR/turtle/) is a key format that is easy to read and use. There is the nicely evolving banana-rdf library for scala  https://github.com/w3c/banana-rdf

Essentially RDF is perfect for doing distributed data. You can map any data format to RDF (using GRDDL for example). Getting this to work with git hashes would be interesting too.

As we build out a [linked data platform](https://dvcs.w3.org/hg/ldpwg/raw-file/default/ldp.html), it will be easier to see how this works. You'd be working on a very well thought out architecture.

It's not something I can put a huge amount of time in right now, but I think it is worth looking into the possibilities there. It would be a pitty not to take the potential given by this into account.

I have a few introductory videos on my home page showing how this can be used to create a social web http://bblfish.net/ . Disitributed code is a social application, so I think this would fit perfectly.

**Comment by harrah** [comment]
Thanks for the feedback!  I will check out the links.  There is now a project and mailing list for collecting and discussing proposals like yours.  Would you mind posting it there?

Mailing list: http://groups.google.com/group/adept-dev/

Project (mainly for the wiki right now): https://github.com/sbt/adept
