### ISSUE TITLE
%% dependencies are resolved using top-level project's scalaVersion, ignoring subproject settings?

### ISSUE THREAD

**Issue by aryairani** [harrah/xsbt#639]
https://github.com/refried/sbt-mixed-scalaversions -- because gist.github doesn't like naming files after subdirs!

**Comment by xuwei-k** [comment]
@refried see [README.md](https://github.com/harrah/xsbt#sbt-has-moved)

![screen shot 2013-06-21 at 9 51 33](https://f.cloud.github.com/assets/389787/684916/c67daafa-da0c-11e2-8772-66ba57fe3bd1.png)

**Comment by aryairani** [comment]
How embarassing...
